[package]
name = "physx-macros"
version = "0.1.0"
authors = ["Embark <opensource@embark-studios.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/EmbarkStudios/physx-rs"
edition = "2018"
readme = "README.md"
keywords = [] # TODO: fill in before publishing
categories = [] # TODO: fill in before publishing
publish = false # not yet

[lib]
proc-macro = true
doctest = false

[dependencies]
syn = { version = "0.15", features = ["full", "extra-traits", "parsing", "printing"] }
quote = "0.6"
proc-macro2 = "0.4"
