[package]
name = "physx"
description = "High-level Rust interface for Nvidia PhysX"
version = "0.1.0"
authors = ["Embark <opensource@embark-studios.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/EmbarkStudios/physx-rs"
edition = "2018"
readme = "README.md"
keywords = ["physics"]
categories = ["api-bindings", "simulation", "game-engines"]

[lib]
doctest = false

[dependencies]
# local dependency for testing
physx-macros = { path = "../physx-macros" }
physx-sys = { path = "../physx-sys" }

# use this after publishing
#physx-macros = "0.1.0"
#physx-sys = "0.1.0+4.1"

enumflags2 = "^0.5"
enumflags2_derive = "^0.5"
floating-duration = "0.1.2"
nalgebra = "0.18.0"
parking_lot = "0.8.0"
ncollide3d = "0.19.0"
nalgebra-glm = "0.4"
log = "0.4"