[package]
name = "physx"
version = "0.1.0"
authors = ["Embark <opensource@embark-studios.com>"]
license = "Embark-Proprietary"
edition = "2018"
publish = false

[lib]
doctest = false

[dependencies]
enumflags2 = "^0.5"
enumflags2_derive = "^0.5"
floating-duration = "0.1.2"
nalgebra = "0.18.0"
parking_lot = "0.8.0"
physx-macros = { path = "../physx-macros" }
physx-sys = { path = "../physx-sys" }
ncollide3d = "0.19.0"
nalgebra-glm = "*"
